name: Build v2rayA for ipk

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: Build packages for aarch64_cortex-a53
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: mediatek-filogic-24.10.6
          FEEDNAME: v2raya_ci
          PACKAGES: ca-certificates luci-app-v2raya v2ray-geodata v2ray-core v2raya xray-core
          NO_REFRESH_CHECK: 1
          V: sc

      - name: Store packages
        uses: actions/upload-artifact@v5
        with:
          name: aarch64_cortex-a53-${{ github.sha }}-packages
          path: bin/packages/aarch64_cortex-a53/v2raya_ci/*.ipk
          if-no-files-found: error
